apiVersion: v1
kind: Template
metadata:
  name: result-api-buildconfig
  annotations:
    description: This is Thoth Core - Results API BuildConfig
    openshift.io/display-name: 'Thoth Core: Result API BuildConfig'
    version: 0.4.0
    tags: poc,thoth,result-api,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Result API BuildConfig, this template is meant to be used by Bots,
      but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: result-api-buildconfig
    app: thoth
    component: result-api

objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: result-api
      labels:
        app: thoth
        component: result-api
    spec:
      resources:
        limits:
          cpu: 2
          memory: 768Mi
        requests:
          cpu: 2
          memory: 768Mi
      output:
        to:
          kind: ImageStreamTag
          name: 'result-api:${IMAGE_STREAM_TAG}'
      source:
        type: Git
        git:
          uri: '${GITHUB_URL}'
          ref: '${GITHUB_REF}'
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-36-centos7:latest
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: ''
            - name: WEB_CONCURRENCY
              value: '4'
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
        - type: Generic
          generic:
            secretReference:
              name: zuul-incoming-webhook

  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: thoth
      name: result-api
    spec:
      name: latest

parameters:
  - description: Name of the github repository for Thoth's Result API
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/result-api'

  - description: Git reference to be used for Thoth's Result API
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
